/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as CareerExplorationIndexRouteImport } from './routes/career-exploration/index'
import { Route as CareerExplorationUsResidencyRouteImport } from './routes/career-exploration/us-residency'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerExplorationIndexRoute = CareerExplorationIndexRouteImport.update({
  id: '/career-exploration/',
  path: '/career-exploration/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerExplorationUsResidencyRoute =
  CareerExplorationUsResidencyRouteImport.update({
    id: '/career-exploration/us-residency',
    path: '/career-exploration/us-residency',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/mentorship': typeof MentorshipRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/career-exploration/us-residency': typeof CareerExplorationUsResidencyRoute
  '/admin/': typeof AdminIndexRoute
  '/career-exploration/': typeof CareerExplorationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/mentorship': typeof MentorshipRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/career-exploration/us-residency': typeof CareerExplorationUsResidencyRoute
  '/admin': typeof AdminIndexRoute
  '/career-exploration': typeof CareerExplorationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/mentorship': typeof MentorshipRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/career-exploration/us-residency': typeof CareerExplorationUsResidencyRoute
  '/admin/': typeof AdminIndexRoute
  '/career-exploration/': typeof CareerExplorationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/join'
    | '/mentorship'
    | '/programs'
    | '/resources'
    | '/team'
    | '/admin/subscriptions'
    | '/career-exploration/us-residency'
    | '/admin/'
    | '/career-exploration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/join'
    | '/mentorship'
    | '/programs'
    | '/resources'
    | '/team'
    | '/admin/subscriptions'
    | '/career-exploration/us-residency'
    | '/admin'
    | '/career-exploration'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/join'
    | '/mentorship'
    | '/programs'
    | '/resources'
    | '/team'
    | '/admin/subscriptions'
    | '/career-exploration/us-residency'
    | '/admin/'
    | '/career-exploration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  JoinRoute: typeof JoinRoute
  MentorshipRoute: typeof MentorshipRoute
  ProgramsRoute: typeof ProgramsRoute
  ResourcesRoute: typeof ResourcesRoute
  TeamRoute: typeof TeamRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  CareerExplorationUsResidencyRoute: typeof CareerExplorationUsResidencyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CareerExplorationIndexRoute: typeof CareerExplorationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-exploration/': {
      id: '/career-exploration/'
      path: '/career-exploration'
      fullPath: '/career-exploration/'
      preLoaderRoute: typeof CareerExplorationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-exploration/us-residency': {
      id: '/career-exploration/us-residency'
      path: '/career-exploration/us-residency'
      fullPath: '/career-exploration/us-residency'
      preLoaderRoute: typeof CareerExplorationUsResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  JoinRoute: JoinRoute,
  MentorshipRoute: MentorshipRoute,
  ProgramsRoute: ProgramsRoute,
  ResourcesRoute: ResourcesRoute,
  TeamRoute: TeamRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  CareerExplorationUsResidencyRoute: CareerExplorationUsResidencyRoute,
  AdminIndexRoute: AdminIndexRoute,
  CareerExplorationIndexRoute: CareerExplorationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
